apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

configMapGenerator:
  - name: nginx-config
    literals:
      - app_name=nginx-production
      - log_level=info

secretGenerator:
  - name: nginx-secret
    literals:
      - db_username=prod_admin
      - db_password=prod_password

generatorOptions:
  disableNameSuffixHash: true
